/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  IWorkspaceRegistry,
  IWorkspaceRegistryInterface,
} from "../IWorkspaceRegistry";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
      {
        internalType: "uint96",
        name: "",
        type: "uint96",
      },
    ],
    name: "eoaToScw",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class IWorkspaceRegistry__factory {
  static readonly abi = _abi;
  static createInterface(): IWorkspaceRegistryInterface {
    return new utils.Interface(_abi) as IWorkspaceRegistryInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IWorkspaceRegistry {
    return new Contract(address, _abi, signerOrProvider) as IWorkspaceRegistry;
  }
}
